name: flutter_calendar_connect_example
description: "Demonstrates how to use the flutter_calendar_connect plugin."
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_connect:
    path: ../
  cupertino_icons: ^1.0.6
  flutter_value_state: ^1.3.6
  value_cubit: ^1.3.3
  flutter_bloc: ^8.1.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true