name: flutter_calendar_connect
description: "A plugin to edit users calendars"
version: 0.0.1
homepage: https://github.com/sncf-connect-tech/flutter_calendar_connect/tree/main

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^22.7.0
  timezone: ^0.10.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.flutter_calendar_connect
        pluginClass: CalendarPlugin
      ios:
        pluginClass: CalendarPlugin