name: easy_calendar
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^22.7.0
  timezone: ^0.10.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.easy_calendar
        pluginClass: EasyCalendarPlugin
      ios:
        pluginClass: EasyCalendarPlugin